### ISSUE TITLE
[ERROR] Use of deleted functions - Cross compiling Spidermonkey for target=riscv64gc 

### ISSUE THREAD

**Issue by dhairyashah1** [plctlab/gecko-dev-riscv#1]
**Aim** - To cross-compile and generate binaries for Spidermonkey(js engine) for **_target=riscv64gc,_** ; **_host = x86_64_** 

**Build Configuration** - 
**Config Log** - [Link](https://pastebin.com/yC4kX0m6)
![Screenshot from 2021-10-19 02-04-07](https://user-images.githubusercontent.com/64425805/137802939-16a02df6-8e78-4fb7-b705-d194dce1f6a1.png)

**Error** - 
1. _[error] use of deleted functions_ in `/gecko-dev-riscv/obj-debug-riscv64-pc-linux-gnu/dist/include/mozilla/*`
2. _[error] use of deleted functions_ in `/gecko-dev-riscv/js/src/builtin/intl/*`

**Error Log** - [Link](https://pastebin.com/ARiHT70R)

**Detailed Build Log** - [Link](https://pastebin.com/wfyUDMRk)

**Mozconfig used** - [Link](https://pastebin.com/VcEvULX0)

**Build fail Log** - 
![Screenshot from 2021-10-19 02-00-52](https://user-images.githubusercontent.com/64425805/137802454-fb0c6541-6262-4d9d-acfb-9656ea209bf4.png)

**Comment by lazyparser** [comment]
I'd suggest that we can reproduce the success of Makoto Kato, apply the patches on develop branch and PR it to plctlab/gecko-dev-riscv. Then the CI can be built (by me). Then try to write the patches for JIT compilers.

**Comment by dhairyashah1** [comment]
To reproduce the success of Makoto Kato, as per the suggestions and testing trials
1. I have established `fedora, Qemu, and tinyEmu` emulator environments as per our goals on the` k9` instance and it seems to work soon. 
2. The issue is that since Qemu is an emulator that lacks and `slows `a bit in performing speed and hence a simple make command also takes a lot of time. the simple `make linux` command for setting `riscv gnu toolchain` takes more than `6 hours.`
3. Simultaneously also getting the same level on `unmatched004` which is a `riscv sifive board` instance. This would yield faster and better results than the emulator. Although I would require the root `apt and make` permission for it. 
4. Also, people in the community were of the opinion that `cross-compiling for riscv` on the native machine/ instance would definitely produce a lot of errors, hence switching to emulator/sifive board instance is the option currently being implemented.
