### ISSUE TITLE
error[E0432]: Cross Compiling firefox browser (gecko-dev-riscv, by makoto kato) for target = riscv64 

### ISSUE THREAD

**Issue by ninja3011** [plctlab/gecko-dev-riscv#2]
## Firefox Code Source 
- [SOURCE](https://github.com/plctlab/gecko-dev-riscv)

## MOZCONFIG Used
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/objdirX
mk_add_options AUTOCLOBBER=1

ac_add_options --enable-application=browser
ac_add_options --disable-debug
ac_add_options --enable-optimize

ac_add_options --target=riscv64
export CC=riscv64-linux-gnu-gcc
export CXX=riscv64-linux-gnu-g++
export HOST_CC=gcc
export HOST_CXX=g++

## Description

**An import was unresolved.**

This occurs most probably due to incorrect rust version usage. The mismatch between the 2015 and 2018 versions. The use of super:: and self:: which is used in the codebase already.

I tried using rustup update to make sure rust was the latest version.

### rustup show to show the rust details

ninad@k9-plct-moz:~/gecko-dev-riscv$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ninad/.rustup

installed targets for active toolchain
-----------------------------'

riscv64gc-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
-----------------------------'

stable-x86_64-unknown-linux-gnu (default)
rustc 1.55.0 (c8dfcfe04 2021-09-06)

## ERROR
 0:36.03 error[E0432]: unresolved imports `super::hidwrapper::_HIDIOCGRDESC`, `super::hidwrapper::_HIDIOCGRDESCSIZE`
 0:36.03   --> /home/ninad/gecko-dev-riscv/third_party/rust/authenticator/src/linux/hidraw.rs:11:25
 0:36.03    |
 0:36.03 11 | use super::hidwrapper::{_HIDIOCGRDESC, _HIDIOCGRDESCSIZE};
 0:36.03    |                         ^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^ no `_HIDIOCGRDESCSIZE` in `platform::hidwrapper`
 0:36.03    |                         |
 0:36.03    |                         no `_HIDIOCGRDESC` in `platform::hidwrapper`
.
.
.
 1:20.10 make[2]: *** [/home/ninad/gecko-dev-riscv/config/recurse.mk:34: compile] Error 2
 1:20.10 make[1]: *** [/home/ninad/gecko-dev-riscv/config/rules.mk:358: default] Error 2
 1:20.10 make: *** [client.mk:54: build] Error 2
 1:20.12 0 compiler warnings present.

**Comment by dlan17** [comment]
hi ninja:
 I'd suggest *NOT* to use  "the cross-compiling" way to build up firefox, there are probably so many problems you will encounter..
 Instead, using qemu user emulation[1] is a more practical way to compile firefox, I've tried on Gentoo Linux, it at least works for me (build out firefox-94 successfully), roughly take about 3hours to do the compiling
 General idea would be like this 1) compiling software (firefox) using qemu-user 2) then deploy the rootfs into real hardware (unleashed?) for run-time test

[1] https://qemu-project.gitlab.io/qemu/user/index.html
https://wiki.debian.org/QemuUserEmulation
https://wiki.gentoo.org/wiki/Embedded_Handbook/General/Compiling_with_qemu_user_chroot

**Comment by ninja3011** [comment]
I have shifted from attempting to cross-compile to set up and run a native build on qemu.

I have overlayed a riscv image on qemu running Fedora Linux. I have yet to build firefox on it. It is taking huge amounts of time for the setups. Will update the results here.

Also, I have created a new folder in the src/jit folder for writing jit files for riscv. Referring to the mips64 files for inferring the flows.

**Comment by dlan17** [comment]
Problem of running native build on qemu is *extremely slow*, the HART will be limited to 8cores if you use mainline qemu version (although PLCT has patches to eliminate the limit)..

I just want to share how to build it on Gentoo using qemu-user-static method.
1) download image[1], and xz -dk 
2) export LOOP_DEV=$(losetup -f)
losetup --offset=$((286720*512)) --sizelimit=$((13631488*512)) ${LOOP_DEV} gentoo-unmatched-2021.10.22.rootfs.wic
mount ${LOOP_DEV} /home/riscv/gentoo_riscv/
3) sh nspawn_rv64d.sh
4) emerge firefox::localrepo

[1] http://8.214.21.40/~dlan/riscv/images/gentoo-unmatched-2021.10.22.rootfs.wic.xz
http://8.214.21.40/~dlan/riscv/images/portage-20211022.squashfs
http://8.214.21.40/~dlan/riscv/script/nspawn_rv64d.sh
http://8.214.21.40/~dlan/riscv/firefox/ (patch & source from makoto kato's, put them at /var/cache/distfiles)
